name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          echo "Triggered by event: ${{ github.event_name }}"
          echo "Branch is ${{ github.ref }} and your repository is ."
      - name: List files in the repository
        run: tree
        shell: bash
